// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// ArrayOfStrings array of strings
//
// swagger:model ArrayOfStrings
type ArrayOfStrings []string

// Validate validates this array of strings
func (m ArrayOfStrings) Validate(formats strfmt.Registry) error {
	return nil
}
